# ── Outputs ─────────────────────────────────────────────────────────
# EC2 outputs are empty when enable_ec2 = false (the default).

output "ec2_public_ip" {
  description = "Public IP — open http://<this>:8000 in a browser"
  value       = var.enable_ec2 ? aws_instance.app[0].public_ip : null
}

output "ec2_public_dns" {
  description = "Public DNS name"
  value       = var.enable_ec2 ? aws_instance.app[0].public_dns : null
}

output "ssh_command" {
  description = "SSH one-liner"
  value = var.enable_ec2 ? (
    "ssh -i ~/.ssh/${var.ssh_key_name}.pem ec2-user@${aws_instance.app[0].public_ip}"
  ) : null
}

# ── Always available (not gated by EC2) ────────────────────────────

output "cognito_user_pool_id" {
  description = "Cognito User Pool ID — set as COGNITO_USER_POOL_ID in .env"
  value       = aws_cognito_user_pool.bheembhai.id
}

output "cognito_client_id" {
  description = "Cognito App Client ID — set as COGNITO_CLIENT_ID in .env"
  value       = aws_cognito_user_pool_client.bheembhai.id
}

output "cognito_user_pool_arn" {
  description = "Cognito User Pool ARN (for IAM policies — needed when enable_ec2 = true)"
  value       = aws_cognito_user_pool.bheembhai.arn
}

output "s3_bucket_name" {
  description = "S3 bucket for step artifacts"
  value       = aws_s3_bucket.artifacts.bucket
}

output "s3_bucket_arn" {
  description = "S3 bucket ARN (for IAM policies)"
  value       = aws_s3_bucket.artifacts.arn
}

# ── Quick-start snippet ─────────────────────────────────────────────
output "env_snippet" {
  description = "Copy these into your .env or docker-compose env block"
  value = join("\n", [
    "# ── Generated by Terraform — copy into .env ──",
    "COGNITO_REGION=${var.aws_region}",
    "COGNITO_USER_POOL_ID=${aws_cognito_user_pool.bheembhai.id}",
    "COGNITO_CLIENT_ID=${aws_cognito_user_pool_client.bheembhai.id}",
    "S3_BUCKET=${aws_s3_bucket.artifacts.bucket}",
    "S3_REGION=${var.aws_region}",
    "SECURE_STORAGE_BACKEND=${local.secure_storage_backend}",
    "AWS_DEFAULT_REGION=${var.aws_region}",
  ])
}
