"""platform-roles-and-sdlc-roles

Revision ID: 698bb9bb1663
Revises: 45b38ccee18c
Create Date: 2026-08-11 11:08:14.839789
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698bb9bb1663'
down_revision: Union[str, None] = '45b38ccee18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_users_platform_role', 'users', "platform_role IN ('ADMIN', 'USER')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_platform_role', 'users', type_='check')
    # ### end Alembic commands ###
